<div class="breadcrumbs">
    <h2 class="secao-azul"><?php echo array_pop($this->title)?></h2>

<?php if($this->controller != 'comparar-imoveis'): ?>
    <!-- AddThis Button BEGIN -->
    <div class="addthis_toolbox addthis_default_style ">
        <a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
        <a class="addthis_button_tweet"></a>
    </div>
    <!-- AddThis Button END -->
<?php endif; ?>
</div>

