<?php
/**
 * iZi Zend Generator
 *
 * @category   iZi
 * @author     Gustavo Henrique Conci
 * @copyright  Copyright (c) 2011 iZi (http://www.izisistemas.com.br)
 * @version    $Id: ##CHILD##.php ##DATAHORA## $
 */

/**
 * This class is used for possible changes in the abstract
 * generated by the Zend iZi Generator.
 */
class ##CHILD## extends ##PARENT## {
	
	##CONTENT##
	
}