<?php
/**
 * iZi Zend Generator
 *
 * @category   iZi
 * @author     Gustavo Henrique Conci
 * @copyright  Copyright (c) 2011 iZi (http://www.izisistemas.com.br)
 * @version    $Id: ##DBTABLE##.php ##DATAHORA## $
 */

/**
 * This class is generated by the iZi Zend Generator
 * and possible changes will be lost the next generation.
 */
class ##DBTABLE## extends ##EXTENDS## {
	
	protected $_name = '##NAME##';
	protected $_rowClass = '##MODEL##';
	protected $_dependentTables = array(##DEPENDENTS##);
	protected $_referenceMap = array(##REFERENCEMAP##);
	protected $_metadata = ##METADATA##;
	##FIND##
}