<?php
/**
 * iZi Zend Generator
 *
 * @category   iZi
 * @author     Gustavo Henrique Conci
 * @copyright  Copyright (c) 2011 iZi (http://www.izisistemas.com.br)
 * @version    $Id: ##FORM##.php ##DATAHORA## $
 */

/**
 * This class is generated by the iZi Zend Generator
 * and possible changes will be lost the next generation.
 */
class ##FORM## extends ##EXTENDS## {
	
	public function init() {
		$this->setName('##NAME##');

	##ELEMENTS##
		parent::init();
	}
	
}