<?php
/**
 * iZi Zend Generator
 *
 * @category   iZi
 * @author     Gustavo Henrique Conci
 * @copyright  Copyright (c) 2011 iZi (http://www.izisistemas.com.br)
 * @version    $Id: ##MODEL##.php ##DATAHORA## $
 */

/**
 * This class is generated by the iZi Zend Generator
 * and possible changes will be lost the next generation.
 */
class ##MODEL## extends ##EXTENDS## {
	
	public function __construct(array $config = array()) {
		$this->_data = array(##DATA##);
		$this->_table = new ##DBTABLE##();
		parent::__construct($config);
    }
	##GETSET##
}