<?php echo $this->headMeta(); ?>

<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title><?php echo implode(' &gt; ', $this->title); ?></title>

<link rel="shortcut icon" href="<?php echo $this->baseUrl;?>/skin/images/favicon.ico" />
<link rel="shortcut icon" href="<?php echo $this->baseUrl;?>/skin/images/favicon.ico" type="image/x-icon" />